deploy test

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -28,9 +28,23 @@ jobs:
 
       - name: Check build result
         run: |
-          if [ -d "dist/apps/front-app/browser" ] && [ -d "dist/apps/front-app/server" ] && [ -d "dist/apps/back-app" ]; then
-            echo "Build completed successfully."
-          else
-            echo "Build failed."
-            exit 1
-          fi
+          if [ -d "dist/apps/front-app/browser" ]; then
+             echo "Build completed successfully."
+           else
+             echo "Build failed [front-app/browser]."
+             exit 1
+           fi
+
+            if [ -d "dist/apps/front-app/server" ]; then
+             echo "Build completed successfully."
+           else
+             echo "Build failed [front-app/server]."
+             exit 1
+           fi
+
+           if [ -d "dist/apps/back-app" ]; then
+             echo "Build completed successfully."
+           else
+             echo "Build failed [back-app]."
+             exit 1
+           fi
