deploy4

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,6 +43,15 @@ jobs:
 
             npm ci
 
+            npm run build-ssr:front
+
+            if [ -d "dist/apps/front-app/browser" ] && [ -d "dist/apps/front-app/server" ] && [ -d "dist/apps/back-app" ]; then
+              echo "Build completed successfully."
+            else
+              echo "Build failed."
+              exit 1
+            fi
+
 
 
 
